### ISSUE TITLE
splunk enterprise security

### ISSUE THREAD

**Issue by fadid** [diogofgm/TA-kaspersky#1]
hi , 
I would like to thank you for sharing the TA , but did you test it with splunk enterprise security?
I had problems in the ES malware dashbords is not wotking.
BR

**Comment by diogofgm** [comment]
You're welcome!
Yes I tested it in ES. Actually I was building it for that end. Can you check if the fields are being extracted in search?

**Comment by fadid** [comment]
hello,
The action field was missing, so I extracted it.but still the malware center dashboards are not working.

**Comment by fadid** [comment]
Is there is any specific fields to search for them?
and data is taged with the malware

**Comment by diogofgm** [comment]
you can find the fields needed for each dashboard/panel in splunk docs [here](http://docs.splunk.com/Documentation/ES/4.7.4/Admin/Dashboardrequirements) 

The action field is being looked up from vendor action to action. I found several actions and this was a way to make them use the same naming convention.

**Comment by fadid** [comment]
ok, but didn't you already mapped them in the TA to CIM model?

**Comment by diogofgm** [comment]
yes

**Comment by kulcsari** [comment]
Hi, I also try to integrate Kaspersky Security Center v10.4 with Splunk. During this process, I noticed that not all the kaspersky (set as default for all incoming events) sourcetype events received a new sourcetype. So I assume the log format could have changed.
What are version Security Center you using?
Do you have a guide about Kaspersky logs? (type, format, meanings, etc?)

(And thank you for publishing this Add-on, this is my first try, to get log CIM compliance).

**Comment by diogofgm** [comment]
I was using KSC 10.2 when I wrote the TA. Back then there was no splunk option on KSC log outputs so I used leef format. Haven't been able to revisit this add-on lately and update it to the new format. As for the events not being affected by sourcetype renaming, there were some events that I didnt knew where to fit them in the CIM so I just didn't. Still the important ones for me at the time  (malware and devices changes) are working.

Can you provide the event type that is missing sourcetype renaming? (should be something after some pipes looking like GNRL_EV_ATTACK_DETECTED )
 
Edit: I opened a new issue [here](https://github.com/devBusters/TA_kaspersky/issues/2)

**Comment by kulcsari** [comment]
@fadid is there any update, progress with feed ES with these logs?

**Comment by fadid** [comment]
Hello,


Actually there is no progress becasue I think the TA is not compliant with CIM version now.


BR

________________________________

**Comment by kulcsari** [comment]
Hi @fadid ,

Did you try to rename the Add-on (directory) for TA-kaspersky? 
Reference: http://docs.splunk.com/Documentation/ES/latest/Install/ImportCustomApps

Regards,
Istvan

**Comment by diogofgm** [comment]
Hi all,
I'm currently working on a project related to splunk so I'm going to be working in this TA as well shortly. 
hang tight!
Regards

**Comment by diogofgm** [comment]
Hi all,
I've rebuilt the add-on and validated the CIM compliancy for the malware and attack tags of the malware datamodel and I get a nice coverage. Since cef is still missing I released it  as v0.1.0 and will be working to improve down the line. It will be available on Splunkbase in few days but you can get the .spl here in the releases tab.
Regards
