### ISSUE TITLE
regex issues

### ISSUE THREAD

**Issue by barakat-abweh** [diogofgm/TA-kaspersky#7]
@diogofgm I've made some changes to regex and I'll make some in future; can you review and merge those changes?

**Comment by diogofgm** [comment]
Hi Barakat,
I just released to Splunkbase a rebuilt version of the add-on. Not available there yet but you can get the .spl here in the releases tab. 
I believe the regex issues are corrected. In any case, if you find any issue, I can have a look.
Regards
