### ISSUE TITLE
Problem extracting data (Fields related)

### ISSUE THREAD

**Issue by marceloyb** [diogofgm/TA-kaspersky#8]
Hi, i downloaded the app and started using it. I had to make some adaptations on the search of the dashboards, since in my Splunk the fields you were searching are not default extracted. The thing is, in some dashboards i managed to do fine in the extracting, but in some others i can't get trustable information. Could you please share how you did your field extraction?

**Comment by marceloyb** [comment]
I checked some logs from yesterday, when i used the "syslog" Source type on the Data Input, and the results are the same that i got using the "kaspersky:leef" Source type, so i don't think the problem is actually the TA. On the Kaspersky SC console the time is correct. The TZ on my profile is GMT -3 (Brasilia). 

When i used the CEF format for the logs the time wasn't showing on the log, but with the LEEF it shows. Could it be related smh?

**Comment by diogofgm** [comment]
From what you're telling me I'm starting to believe its safe to assume that regardless the time you have in Kaspersky server, LEEF will always output UTC. If that's the case, its just a matter of adding TZ to the "kaspersky:leef" source type. Can you test adding TZ = UTC to the source type in the TA and index some data?

**Comment by marceloyb** [comment]
add TZ = UTC to the /etc/apps/TA-kaspersky/default/props.conf file, right? Did and still keeps the same.

This is the config on the "kaspersky:leef" source type regarding Timestamp

![image](https://user-images.githubusercontent.com/20404114/66841182-add66d80-ef3f-11e9-92f7-be2774eaf5c6.png)

**Comment by diogofgm** [comment]
have you restarted Splunk after that?

**Comment by marceloyb** [comment]
Yes. I was looking the logs and on some of them, the time was -1 instead of the +4. I don't remember what exactly i did after that, but it involved reinstalling TA and messing in the configurations 

![image](https://user-images.githubusercontent.com/20404114/66851767-d8c9bd00-ef51-11e9-8a0d-336ae75ef862.png)

**Comment by diogofgm** [comment]
Ok ive been looking into my data and it seams that my thesis is correct. LEEF outputs in UTC/GMT. I have 1h diference in my data because we are in DST with means GMT+1. I’m going to fix this TZ issue and release an update.

**Comment by diogofgm** [comment]
The new version of the add on has been released in splunkbase. Please check if it solves your issue.
