### ISSUE TITLE
Any Graph not shown data

### ISSUE THREAD

**Issue by omidsky** [diogofgm/TA-kaspersky#9]
hello i download splunkapp and add on from splunkbase and i installed on splunk enterprise but i have a problem all dashboards such as kaspersky Toverview and hosts and Threats dont show any data
i changed macro value to my index only i found data on Reporting Servers and Events over time by type sections please help me for resolve this problems thank you so much

**Comment by diogofgm** [comment]
Ok ive been looking into my data and it seams that my thesis is correct. LEEF outputs in UTC/GMT. I have 1h diference in my data because we are in DST with means GMT+1. I’m going to fix this TZ issue and release an update.

**Comment by diogofgm** [comment]
A new version of the add on has been released in splunkbase. Please check if it solves your issue.
